Setup Payload CMS
kaogeek/hack-th pull request #8
Opened 2023-06-08 15:00 UTC by heypoom

Setting up the Payload CMS according to @bombnp's suggestions.

2023-06-08 15:08 UTC, bombnp commented
That's crazy fast lol. Will review after dinner kub.

2023-06-08 16:05 UTC, bombnp requested changes

2023-06-08 16:05 UTC, bombnp commented on cms/.gitignore
> +
add `build/`, this folder is created during `pnpm build`

2023-06-08 16:07 UTC, bombnp commented
The `Dockerfile` generated from create-payload-app is horrible lmao. I'll make a new one that uses pnpm. Can I push to this branch directly?

2023-06-08 16:18 UTC, heypoom commented
yep feel free to @bombnp

2023-06-08 16:18 UTC, heypoom commented on cms/.prettierrc
> +  "plugins": ["prettier-plugin-astro"],
good catch - copied that from the parent .prettierrc. will fix

2023-06-08 16:23 UTC, rayriffy approved these changes
i think at this point maybe we have to move sites into pnpm workspaces. but this could be done in future PR

2023-06-08 16:36 UTC, bombnp approved these changes
There are potential improvements to `payload.config.ts`, but let's leave it to next PRs.

Looks good to me!

2023-06-09 11:52 UTC, heypoom commented
okie merged - thanks @bombnp @rayriffy!

2023-06-09 11:52 UTC, merged